> pandas是贯穿本书后续部分的主要工具。它所包含的**数据结构**和**数据处理工具**的设计使得在Python中进行**数据清洗**和**分析**非常快捷。pandas经常是和其他数值计算工具，比如NumPy和SciPy，以及数据可视化工具比如matplotlib一起使用的。pandas**支持大部分NumPy语言风格的数组计算**，尤其是**数组函数**以及**没有for循环的各种数据处理**。
尽管pandas采用了很多NumPy的代码风格，但最大的不同在于pandas是用来处理表格型或异质型数据的。而NumPy则相反，它更适合处理同质型的数值类数组数据。
由于在2010年成为了开源项目，pandas已经逐渐成熟，成为一个在真实世界中广泛应用的大型类库。pandas的开发者社区已经有超过800个代码贡献者，他们帮助构建了项目，并将pandas应用到日常中去解决他们的数据难题。
格式引文：
[美] Wes McKinney著.利用Python进行数据分析（原书第2版）.机械工业出版社华章分社.2018:168.
得到电子书：https://d.dedao.cn/DySekAdnNwqfSbtE

前言提示：pandas可以实现这样几个目标：
- 作为数据结构：那么它的结构是如何的，能够存储什么样的数据（找重点）
- 作为数据处理工具：针对不同的数据，它提供了什么方法，给这些数据使用（找重点）
- pandas如何清洗数据
- pandas如何分析数据
- 与numpy的对比，【numpy的数组函数】与ndas的比较，【没有for循环的数据处理】与pandas的比较

## Series

In [1]:
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

#### 这里的values是numpy的ndarray

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

如果是使用obj.values() 方法是不行的，报错

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])

In [6]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2[['a','b']]

a   -5
b    7
dtype: int64

In [8]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [9]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [10]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [11]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
'b' in obj2

True

In [13]:
'e' in obj2

False

In [14]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [15]:
obj3 = pd.Series(sdata)

In [16]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [17]:
states = ['California','Ohio','Oregon','Texas']

In [18]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [21]:
obj4.isnull

<bound method Series.isnull of California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64>

In [22]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

自动对齐索引，在pd的设计风格当中，始终贯彻计算时 结果索引为运算成员的并集，值如果缺失按照一定策略进行填充

In [24]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
obj4.name = 'population'
obj4.index.name = 'state'

In [27]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [28]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [29]:
obj.index = ['Bob','Steve','Jeff','Ryan']

这里的赋值，数量要严格符合元素的数量，跟前面的索引对齐的方式是不一样的

In [30]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

##### 构造Dataframe
pd.DataFrame({key:list})

In [31]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002,2003],'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [32]:
frame = pd.DataFrame(data)

In [33]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [34]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

可以指定列的顺序，列不包含在字典，**会出现缺省值**

In [35]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

指定的index**必须跟字典的index数量完全匹配**，否则报错

In [36]:
frame2 = pd.DataFrame(data, columns = ['year','state','pop','debt'], index=['one','two','three','four','five','hahaha'])

In [37]:
frame2

year   state  pop debt
one     2000    Ohio  1.5  NaN
two     2001    Ohio  1.7  NaN
three   2002    Ohio  3.6  NaN
four    2001  Nevada  2.4  NaN
five    2002  Nevada  2.9  NaN
hahaha  2003  Nevada  3.2  NaN

列直接通过中括号，索引标志进行索引

In [38]:
frame2['year']

one       2000
two       2001
three     2002
four      2001
five      2002
hahaha    2003
Name: year, dtype: int64

In [39]:
frame_test_1 = pd.DataFrame(data, columns=['state','yyy'], index = ['one','two','three','four','five','six'])
frame_test_1

state  yyy
one      Ohio  NaN
two      Ohio  NaN
three    Ohio  NaN
four   Nevada  NaN
five   Nevada  NaN
six    Nevada  NaN

In [40]:
frame2.year

one       2000
two       2001
three     2002
four      2001
five      2002
hahaha    2003
Name: year, dtype: int64

行则需要通过**loc特殊属性**(不是方法，loc后面跟中括号)进行获取

In [41]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [42]:
frame2

year   state  pop debt
one     2000    Ohio  1.5  NaN
two     2001    Ohio  1.7  NaN
three   2002    Ohio  3.6  NaN
four    2001  Nevada  2.4  NaN
five    2002  Nevada  2.9  NaN
hahaha  2003  Nevada  3.2  NaN

In [43]:
frame2['debt'] = 16.5

In [44]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5  16.5
two     2001    Ohio  1.7  16.5
three   2002    Ohio  3.6  16.5
four    2001  Nevada  2.4  16.5
five    2002  Nevada  2.9  16.5
hahaha  2003  Nevada  3.2  16.5

In [45]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one     2000    Ohio  1.5   0.0
two     2001    Ohio  1.7   1.0
three   2002    Ohio  3.6   2.0
four    2001  Nevada  2.4   3.0
five    2002  Nevada  2.9   4.0
hahaha  2003  Nevada  3.2   5.0

In [46]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

In [47]:
frame2['debt'] = val
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     2001    Ohio  1.7  -1.2
three   2002    Ohio  3.6   NaN
four    2001  Nevada  2.4  -1.5
five    2002  Nevada  2.9  -1.7
hahaha  2003  Nevada  3.2   NaN

In [48]:
frame2.loc['state','one'] = 'Ohio'
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt   one  eastern
one     2000.0    Ohio  1.5   NaN   NaN     True
two     2001.0    Ohio  1.7  -1.2   NaN     True
three   2002.0    Ohio  3.6   NaN   NaN     True
four    2001.0  Nevada  2.4  -1.5   NaN    False
five    2002.0  Nevada  2.9  -1.7   NaN    False
hahaha  2003.0  Nevada  3.2   NaN   NaN    False
state      NaN     NaN  NaN   NaN  Ohio    False

In [49]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [50]:
del frame2['eastern']

In [51]:
frame2

year   state  pop  debt   one
one     2000.0    Ohio  1.5   NaN   NaN
two     2001.0    Ohio  1.7  -1.2   NaN
three   2002.0    Ohio  3.6   NaN   NaN
four    2001.0  Nevada  2.4  -1.5   NaN
five    2002.0  Nevada  2.9  -1.7   NaN
hahaha  2003.0  Nevada  3.2   NaN   NaN
state      NaN     NaN  NaN   NaN  Ohio

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'one'], dtype='object')

##### 构造DataFrame
{key:{s_key1:s_value1,s_key2:s_value2,...}}

In [53]:
pop = {'Nevada':{2001:2.4, 2002:2.9}, 'Ohio':{2000:1.5, 2001:1.7,2002:3.6}}

In [54]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [55]:
frame3 = pd.DataFrame(pop)

In [56]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [57]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [58]:
pd.DataFrame(pop, index=[2003,2002,2001])

Nevada  Ohio
2003     NaN   NaN
2002     2.9   3.6
2001     2.4   1.7

In [59]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [60]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [61]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [62]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [63]:
frame3.index = [2000,2001,2002]

In [64]:
frame3

state  Nevada  Ohio
2000      2.4   1.7
2001      2.9   3.6
2002      NaN   1.5

In [65]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [66]:
frame3 = pd.DataFrame(pop, index = [2000,2001,2002])

In [67]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [68]:
frame3.index.name = 'year';frame3.columns.name = 'state'

In [69]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [70]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [71]:
frame2.values

array([[2000.0, 'Ohio', 1.5, nan, nan],
       [2001.0, 'Ohio', 1.7, -1.2, nan],
       [2002.0, 'Ohio', 3.6, nan, nan],
       [2001.0, 'Nevada', 2.4, -1.5, nan],
       [2002.0, 'Nevada', 2.9, -1.7, nan],
       [2003.0, 'Nevada', 3.2, nan, nan],
       [nan, nan, nan, nan, 'Ohio']], dtype=object)

#### 总结，DataFrame构造函数有效输入

#### 索引对象

In [72]:
obj = pd.Series(range(3), index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [73]:
index = obj.index

In [74]:
index

Index(['a', 'b', 'c'], dtype='object')

In [75]:
index[1:]

Index(['b', 'c'], dtype='object')

In [76]:
labels = pd.Index(np.arange(3))

In [77]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [78]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [79]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [80]:
obj2.index is labels

True

In [81]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [82]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [83]:
'Ohio' in frame3.columns

True

In [84]:
2003 in frame3.index

False

In [85]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [86]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [87]:
dup_labels.unique()

Index(['foo', 'bar'], dtype='object')

In [88]:
dup_labels.is_unique

False

In [89]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [90]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [91]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [92]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [93]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

在重建索引的过程当中，差值的逻辑可以指定，如下例

In [94]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [95]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index = ['a','c','d'], columns=['Ohio', 'Texas','California'])

In [96]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [97]:
frame2 = frame.reindex(['a','b','c','d','e'])

In [98]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
e   NaN    NaN         NaN

In [99]:
frame2 = frame2.drop(index='e')

In [100]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [101]:
states = ['Texas', 'Utah', 'California']

列也可以重建索引，需要指明关键字columns，如果不指明，认为是重建行索引

In [102]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [103]:
try:
    frame.loc[['a','c','d'], states]
except KeyError as error:
    print('KeyError', error)

KeyError "['Utah'] not in index"


In [104]:
frame.index

Index(['a', 'c', 'd'], dtype='object')

In [105]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [106]:
frame.index

Index(['a', 'c', 'd'], dtype='object')

In [107]:
frame.columns

Index(['Ohio', 'Texas', 'California'], dtype='object')

In [108]:
states

['Texas', 'Utah', 'California']

In [109]:
frame.loc[['a','c'],['Ohio','Texas']]

Ohio  Texas
a     0      1
c     3      4

In [110]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])

In [111]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [112]:
new_obj = obj.drop('c')

In [113]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [114]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [115]:
obj.drop(['a','c'])

b    1.0
d    3.0
e    4.0
dtype: float64

In [116]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one','two','three','four'])

In [117]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

drop默认是按照行索引index进行删除，即沿着0轴，axis=0进行删除，如果需要沿着1轴进行处理，需要通过axis参数显式指定

In [119]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [120]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [121]:
obj.drop('c', inplace=True)

In [122]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

#### 索引选择和过滤

In [123]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])

In [124]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [125]:
obj['b']

1.0

In [126]:
obj[1]

1.0

In [127]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [128]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [129]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [130]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [131]:
obj < 2

a     True
b     True
c    False
d    False
dtype: bool

重点：Series的切片**包含尾部**，与普通python不相同

In [132]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [133]:
obj['b':'c'] = 5

In [134]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [135]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index = ['Ohio', 'Colorado', 'Utah', 'New York'], columns = ['one', 'two', 'three', 'four'])

In [136]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [137]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [138]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [139]:
data['Ohio':'New York']

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [140]:
data[1:3]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [141]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [142]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### 特殊案例，与先前风格非常不同的设计
- DataFrame的直接的指定索引调用 如 data\['a'\] 或者 data\[\['a','b','c'\]\]这种形式，是按照columns索引来进行识别的
- DataFrame的直接的索引切片，如data\['a':'b'\] 或者 data\[1:3\]，是按照index行索引进行识别的
- DataFrame的直接的布尔索引，也是按照index行索引进行匹配的

#### 所以如果需要统一风格的索引方式，还是使用特殊索引符号loc和iloc

In [143]:
data.loc['Colorado':, ['two', 'three']]

two  three
Colorado    5      6
Utah        9     10
New York   13     14

In [144]:
data.loc[['Utah','New York'], ['two','one']]

two  one
Utah        9    8
New York   13   12

In [145]:
data.iloc[1:,1:]

two  three  four
Colorado    5      6     7
Utah        9     10    11
New York   13     14    15

In [146]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [147]:
data.iloc[0:1,0:1]

one
Ohio    0

In [148]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [149]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [150]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [151]:
data.iloc[[2], :][data > 9]

one  two  three  four
Utah  NaN  NaN     10    11

In [152]:
data.iloc[0,[1]]

two    1
Name: Ohio, dtype: int32

In [153]:
data.iloc[0,0]

0

In [154]:
data.reindex(['Changchun', 'Jilin', 'Colorado'])

one  two  three  four
Changchun  NaN  NaN    NaN   NaN
Jilin      NaN  NaN    NaN   NaN
Colorado   4.0  5.0    6.0   7.0

In [155]:
arr_test = [1,2,3,4]

In [156]:
arr_test[-1]

4

In [157]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [158]:
ser2 = pd.Series(np.arange(3.), index = ['a','b','c'])

In [159]:
ser2[-1]

2.0

In [160]:
ser[:1]

0    0.0
dtype: float64

In [161]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [162]:
ser.iloc[:1]

0    0.0
dtype: float64

In [163]:
ser.add(4, 4.)

0    4.0
1    5.0
2    6.0
dtype: float64

In [164]:
ser[4] = 4.

In [165]:
ser[3] = 3.

In [166]:
ser

0    0.0
1    1.0
2    2.0
4    4.0
3    3.0
dtype: float64

##### DataFrame【增】加列

In [167]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [168]:
data['five'] = [100,101,102,103]

In [169]:
data

one  two  three  four  five
Ohio        0    1      2     3   100
Colorado    4    5      6     7   101
Utah        8    9     10    11   102
New York   12   13     14    15   103

##### DataFrame【增】加行

In [170]:
data.loc['Texes'] = [1,2,3,4,5]

In [171]:
data

one  two  three  four  five
Ohio        0    1      2     3   100
Colorado    4    5      6     7   101
Utah        8    9     10    11   102
New York   12   13     14    15   103
Texes       1    2      3     4     5

In [172]:
data.iloc[[1]]

one  two  three  four  five
Colorado    4    5      6     7   101

In [173]:
data.loc['Ohio', 'one'] = 17777

In [174]:
data

one  two  three  four  five
Ohio      17777    1      2     3   100
Colorado      4    5      6     7   101
Utah          8    9     10    11   102
New York     12   13     14    15   103
Texes         1    2      3     4     5

#### DataFrame算数

算数索引自动对齐

In [175]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])

In [176]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [177]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a','c','e','f','g'])

In [178]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [179]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [180]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [181]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [182]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [183]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [184]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [185]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [186]:
df_test = pd.DataFrame({'A':[1,2]})

In [187]:
df_test1 = pd.DataFrame({'B':[3,4]})

In [188]:
df_test

A
0  1
1  2

In [189]:
df_test1

B
0  3
1  4

In [190]:
df_test + df_test1

A   B
0 NaN NaN
1 NaN NaN

In [191]:
df_test - df_test1

A   B
0 NaN NaN
1 NaN NaN

自动对齐 有缺失值的问题（NaN），可以通过调用**计算函数 并 传入fill_value参数** 将缺失值先进行填充，然后参与计算

In [192]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))

In [193]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

In [194]:
df2.loc[1, 'b'] = np.nan

In [195]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [196]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [197]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [198]:
df1.add(df2, fill_value=10000)

a        b        c        d        e
0      0.0      2.0      4.0      6.0  10004.0
1      9.0  10005.0     13.0     15.0  10009.0
2     18.0     20.0     22.0     24.0  10014.0
3  10015.0  10016.0  10017.0  10018.0  10019.0

In [199]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [200]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [201]:
df1.reindex(columns=df2.columns, fill_value=10000)

a    b     c     d      e
0  0.0  1.0   2.0   3.0  10000
1  4.0  5.0   6.0   7.0  10000
2  8.0  9.0  10.0  11.0  10000

In [202]:
df1.radd(df2, fill_value = 10000)

a        b        c        d        e
0      0.0      2.0      4.0      6.0  10004.0
1      9.0  10005.0     13.0     15.0  10009.0
2     18.0     20.0     22.0     24.0  10014.0
3  10015.0  10016.0  10017.0  10018.0  10019.0

In [203]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [204]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [205]:
df1 - df2

a    b    c    d   e
0  0.0  0.0  0.0  0.0 NaN
1 -1.0  NaN -1.0 -1.0 NaN
2 -2.0 -2.0 -2.0 -2.0 NaN
3  NaN  NaN  NaN  NaN NaN

In [206]:
df2 - df1

a    b    c    d   e
0  0.0  0.0  0.0  0.0 NaN
1  1.0  NaN  1.0  1.0 NaN
2  2.0  2.0  2.0  2.0 NaN
3  NaN  NaN  NaN  NaN NaN

In [207]:
df2.rsub(df1, fill_value = 10000)

a       b       c       d       e
0     0.0     0.0     0.0     0.0  9996.0
1    -1.0 -9995.0    -1.0    -1.0  9991.0
2    -2.0    -2.0    -2.0    -2.0  9986.0
3  9985.0  9984.0  9983.0  9982.0  9981.0

In [208]:
arr = np.arange(12.).reshape((3,4))

In [209]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [210]:
arr[0]

array([0., 1., 2., 3.])

DataFrame与Series之间的相互计算，会在df当中进行**广播**

In [211]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

**np 的ndarray每一行都进行了减法操作**

In [212]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index = ['Utah','Ohio','Texas','Oregon'])

In [213]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [214]:
series = frame.iloc[0]

In [215]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [216]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [217]:
series2 = pd.Series(range(3), index=['b','e','f'])

In [218]:
series2

b    0
e    1
f    2
dtype: int64

In [219]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [220]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

DataFrame与Series进行计算会出现自动对齐的地方必有计算一方有值缺失，可以选择使用fill_value定制其他值进行填充计算

In [221]:
series3 = frame['d']

In [222]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [223]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

这里axis='index'其实并不是一个一致的理解，一般的理解是【沿着】index轴，但是这个广播显然是沿着columns轴进行的 **有问题！！**

In [224]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [225]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

**axis=0轴是index轴，也就是纵轴，axis=1是columns轴，也就是横轴**

In [226]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [227]:
frame

b         d         e
Utah    1.186404  0.059089 -1.494129
Ohio    0.590977  1.425670 -0.524228
Texas  -0.564286  0.546573 -1.488762
Oregon  0.219363  0.007808  0.088892

In [228]:
np.abs(frame)

b         d         e
Utah    1.186404  0.059089  1.494129
Ohio    0.590977  1.425670  0.524228
Texas   0.564286  0.546573  1.488762
Oregon  0.219363  0.007808  0.088892

np的通用函数对于pd也是有效的

In [229]:
frame.abs()

b         d         e
Utah    1.186404  0.059089  1.494129
Ohio    0.590977  1.425670  0.524228
Texas   0.564286  0.546573  1.488762
Oregon  0.219363  0.007808  0.088892

#### 函数的应用与映射

In [230]:
f = lambda x : x.max() - x.min()

In [231]:
frame.apply(f)

b    1.750689
d    1.417862
e    1.583021
dtype: float64

【通用函数】是针对数据结构的每个元素调用一次，DataFrame当中元素是指，单个的**列向量**（默认）或者是**行向量**（需要用参数指定）

In [232]:
frame.apply(f, axis='columns')

Utah      2.680532
Ohio      1.949898
Texas     2.035336
Oregon    0.211555
dtype: float64

指定axis='columns'的理解：因为f作为一个lambda匿名函数是需要作用于每个**元素**的，axis就是指定将**哪个轴看成是一个元素**，即将columns轴看成一个元素之后，它们会内部（按照**行**）进行f运算，然后输出的结果是一**列**

In [233]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

In [234]:
frame.apply(f, axis = 'columns')

min       max
Utah   -1.494129  1.186404
Ohio   -0.524228  1.425670
Texas  -1.488762  0.546573
Oregon  0.007808  0.219363

In [235]:
format = lambda x : '%.2f' % x

In [236]:
frame.applymap(format)

b     d      e
Utah     1.19  0.06  -1.49
Ohio     0.59  1.43  -0.52
Texas   -0.56  0.55  -1.49
Oregon   0.22  0.01   0.09

***applymap***函数是**逐个元素**的函数，***apply***是表中的行/列Series为单位的

In [237]:
format1 = lambda x : '{:.2f}'.format(x)
frame.applymap(format1)

b     d      e
Utah     1.19  0.06  -1.49
Ohio     0.59  1.43  -0.52
Texas   -0.56  0.55  -1.49
Oregon   0.22  0.01   0.09

format1采用了新式的格式化函数处理字符串，一样好用！

In [238]:
obj = pd.Series(range(4), index=['d','a','b','c'])

In [239]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [240]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), index = ['three', 'one'], columns = ['d', 'a', 'b', 'c'])

In [241]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [242]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [243]:
frame.sort_index(axis = 1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [244]:
obj = pd.Series([4,7,-3,2])

In [245]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [246]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [247]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [248]:
frame = pd.DataFrame({'b':[4,7,-3,2], 'a':[0,1,0,1]})

In [249]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [250]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [251]:
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

优先级排序，先按照‘a’列进行排序，值相同的再参考‘b’列进行排序

In [252]:
obj = pd.Series([7,-5,7,4,2,0,4,4,4])

In [253]:
obj.rank()

0    8.5
1    1.0
2    8.5
3    5.5
4    3.0
5    2.0
6    5.5
7    5.5
8    5.5
dtype: float64

In [254]:
obj.rank(method='first')

0    8.0
1    1.0
2    9.0
3    4.0
4    3.0
5    2.0
6    5.0
7    6.0
8    7.0
dtype: float64

默认：相同大小的元素,会将次序取平均数,然后分享这个相同的值作为rank；'first'：整体按照从小到大顺序, 如果是相同的元素,按照**出现次序**先出现的排在前面 

In [255]:
obj.rank(ascending=True, method='max')

0    9.0
1    1.0
2    9.0
3    7.0
4    3.0
5    2.0
6    7.0
7    7.0
8    7.0
dtype: float64

如果是相同的元素，每个元素都取所有元素当中最大的那个序号

In [256]:
frame = pd.DataFrame({'b': [4.3,7,-3,2], 'a':[0,1,0,1], 'c':[-2,5,8,-2.5]})

In [257]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [258]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [259]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])

In [260]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [261]:
a = {'b':2,'b':3}

In [262]:
a

{'b': 3}

python 内置的字典，相同键会**覆盖**，Series则会完全保留

In [263]:
obj.index.is_unique

False

In [264]:
obj['a']

a    0
a    1
dtype: int64

In [265]:
obj['c']

4

In [266]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])

In [267]:
df

0         1         2
a  2.335209 -0.738140  1.470634
a  1.989928  1.106692 -0.083901
b  0.661706 -0.409301  0.247031
b -0.608688  1.383718 -0.129853

In [268]:
df.loc['b']

0         1         2
b  0.661706 -0.409301  0.247031
b -0.608688  1.383718 -0.129853

### 以下为【描述性统计】部分

In [269]:
df = pd.DataFrame([[1.4,np.nan], [7.1,-4.5],[np.nan, np.nan],[0.75, -1.3]], index = ['a', 'b', 'c', 'd'], columns = ['one', 'two'])

In [270]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [271]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [272]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [273]:
df.sum(axis = 'columns', skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [274]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [275]:
df.idxmax()

one    b
two    d
dtype: object

In [276]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [277]:
df.idxmin(axis = 'columns')

a    one
b    two
c    NaN
d    two
dtype: object

idxmin 和 idxmax 是在一个轴方向上寻找 最小/大值的坐标

In [278]:
from pandas_datareader import data

In [279]:
tickers = ['AAPL', 'IBM', 'MSFT','GOOG','0700.HK']
start_date = '2022-01-01'
end_date = '2022-03-31'

# all_data = data.get_data_yahoo('AAPL',start_date, end_date)
all_data = {ticker : data.DataReader(ticker,'yahoo', start_date, end_date) for ticker in tickers}

需要代理获取这部分数据

In [280]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2021-12-31  179.229996  177.259995  178.089996  177.570007   64062300.0   
 2022-01-03  182.880005  177.710007  177.830002  182.009995  104487900.0   
 2022-01-04  182.940002  179.119995  182.630005  179.699997   99310400.0   
 2022-01-05  180.169998  174.639999  179.610001  174.919998   94537600.0   
 2022-01-06  175.300003  171.639999  172.699997  172.000000   96904000.0   
 ...                ...         ...         ...         ...          ...   
 2022-03-25  175.279999  172.750000  173.880005  174.720001   80546200.0   
 2022-03-28  175.729996  172.000000  172.169998  175.600006   90371900.0   
 2022-03-29  179.009995  176.339996  176.690002  178.960007  100589400.0   
 2022-03-30  179.610001  176.699997  178.550003  177.770004   92633200.0   
 2022-03-31  178.029999  174.399994  177.839996  174.610001  103049300.0   
 
  

In [281]:
type(all_data)

dict

In [282]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})

In [283]:
price

AAPL         IBM        MSFT         GOOG     0700.HK
Date                                                                   
2021-12-31  177.344055  132.069168  335.626038  2893.590088         NaN
2022-01-03  181.778397  134.420822  334.059265  2901.489990  453.799988
2022-01-04  179.471344  136.377274  328.331116  2888.330078  450.000000
2022-01-05  174.697418  136.574890  315.727173  2753.070068  430.600006
2022-01-06  171.781143  133.729156  313.232330  2751.020020  437.000000
...                ...         ...         ...          ...         ...
2022-03-25  174.720001  131.350006  303.679993  2830.429932  356.399994
2022-03-28  175.600006  131.470001  310.700012  2839.000000  366.399994
2022-03-29  178.960007  131.940002  315.410004  2865.000000  377.200012
2022-03-30  177.770004  132.130005  313.859985  2852.889893  380.600006
2022-03-31  174.610001  130.020004  308.309998  2792.989990  374.200012

[65 rows x 5 columns]

In [284]:
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [285]:
volume

AAPL        IBM        MSFT       GOOG     0700.HK
Date                                                                 
2021-12-31   64062300.0  3362100.0  18000800.0   864900.0         NaN
2022-01-03  104487900.0  4605900.0  28865100.0  1260700.0   6021146.0
2022-01-04   99310400.0  7300000.0  32674300.0  1146400.0  13562081.0
2022-01-05   94537600.0  8956900.0  40054300.0  2482100.0  31926972.0
2022-01-06   96904000.0  9908100.0  39646100.0  1452500.0  22394447.0
...                 ...        ...         ...        ...         ...
2022-03-25   80546200.0  3530200.0  22566500.0   963500.0  38297070.0
2022-03-28   90371900.0  2483500.0  29578200.0  1188700.0  26933320.0
2022-03-29  100589400.0  5791000.0  30393400.0  1433900.0  20901992.0
2022-03-30   92633200.0  2622900.0  28163600.0  1052300.0  26951872.0
2022-03-31  103049300.0  4274000.0  33422100.0  1475800.0  14589554.0

[65 rows x 5 columns]

In [286]:
returns = price.pct_change()

In [287]:
returns.tail()

AAPL       IBM      MSFT      GOOG   0700.HK
Date                                                        
2022-03-25  0.003734  0.016248 -0.001381  0.001483 -0.026230
2022-03-28  0.005037  0.000914  0.023117  0.003028  0.028058
2022-03-29  0.019134  0.003575  0.015159  0.009158  0.029476
2022-03-30 -0.006650  0.001440 -0.004914 -0.004227  0.009014
2022-03-31 -0.017776 -0.015969 -0.017683 -0.020996 -0.016816

In [288]:
returns['MSFT'].corr(returns['IBM'])

0.15255045134009407

In [289]:
returns['MSFT'].cov(returns['IBM'])

4.080912828606558e-05

In [290]:
returns.corr()

AAPL       IBM      MSFT      GOOG   0700.HK
AAPL     1.000000  0.363900  0.773290  0.735885  0.194251
IBM      0.363900  1.000000  0.152550  0.234666 -0.013297
MSFT     0.773290  0.152550  1.000000  0.843603  0.164502
GOOG     0.735885  0.234666  0.843603  1.000000  0.231425
0700.HK  0.194251 -0.013297  0.164502  0.231425  1.000000

In [291]:
returns.cov()

AAPL       IBM      MSFT      GOOG   0700.HK
AAPL     0.000355  0.000090  0.000297  0.000304  0.000154
IBM      0.000090  0.000172  0.000041  0.000067 -0.000007
MSFT     0.000297  0.000041  0.000415  0.000377  0.000143
GOOG     0.000304  0.000067  0.000377  0.000480  0.000216
0700.HK  0.000154 -0.000007  0.000143  0.000216  0.001783

In [292]:
returns.corrwith(returns.IBM)

AAPL       0.363900
IBM        1.000000
MSFT       0.152550
GOOG       0.234666
0700.HK   -0.013297
dtype: float64

In [293]:
returns.corrwith(volume, axis = 'columns')

Date
2021-12-31         NaN
2022-01-03    0.582352
2022-01-04   -0.491943
2022-01-05   -0.024381
2022-01-06   -0.344053
                ...   
2022-03-25   -0.246511
2022-03-28    0.048967
2022-03-29    0.378426
2022-03-30   -0.368428
2022-03-31    0.098039
Freq: B, Length: 65, dtype: float64

In [294]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [295]:
uniques = obj.unique()

In [296]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [297]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [298]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [299]:
mask = obj.isin(['b','c'])

In [300]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [301]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [302]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [303]:
unique_vals = pd.Series(['c','b','a'])

In [304]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [305]:
pd.Index(unique_vals)

Index(['c', 'b', 'a'], dtype='object')

In [306]:
data = pd.DataFrame({'Qu1': [10,30,40,30,40],'Qu2': [20,30,10,20,30],'Qu3': [10,50,20,40,40]})

In [307]:
data

Qu1  Qu2  Qu3
0   10   20   10
1   30   30   50
2   40   10   20
3   30   20   40
4   40   30   40

In [308]:
result = data.apply(pd.value_counts).fillna(0)

In [309]:
result

Qu1  Qu2  Qu3
10  1.0  1.0  1.0
20  0.0  2.0  1.0
30  2.0  2.0  0.0
40  2.0  0.0  2.0
50  0.0  0.0  1.0